import os

class Config:
    AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_EASTUS2_API_KEY")
    AZURE_OPENAI_URL = os.getenv("AZURE_OPENAI_EASTUS2_URL")
    AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_EASTUS2_API_VERSION", "2024-02-15-preview")
    AZURE_OPENAI_MODEL = os.getenv("AZURE_OPENAI_EASTUS2_MODEL", "gpt-4o")